# Generated by Django 4.1.6 on 2024-05-29 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=350)),
                ('housenumber', models.IntegerField()),
                ('postalcode', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=1000)),
                ('sendingtime', models.CharField(max_length=1000)),
                ('receivername', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'فروش',
            },
        ),
        migrations.AddField(
            model_name='makeup',
            name='shopname',
            field=models.ForeignKey(default=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AddField(
            model_name='skincare',
            name='shopname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='makeup.shop'),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='productname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='remained',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopname',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopphonenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')]),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='price',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='productname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='remained',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationalcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userphonenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\d{10,14}')]),
        ),
        migrations.CreateModel(
            name='Digitalstuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('remained', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=7)),
                ('maincategory', models.CharField(max_length=20)),
                ('brandname', models.CharField(max_length=20)),
                ('aboutproduct', models.TextField(max_length=350)),
                ('manufacturing_country', models.CharField(max_length=20)),
                ('warranty', models.IntegerField()),
                ('shopname', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='makeup.shop')),
            ],
            options={
                'verbose_name': 'لوازم برقی',
            },
        ),
    ]
